services:
  - type: web
    name: mundo-patas-veterinaria
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mundo-patas-db
          property: connectionString
  
databases:
  - name: mundo-patas-db
    databaseName: mundopatas
    user: mundopatas
    plan: free
